schemaVersion: "1.2"
name: hello-choreo-php
services:
  - name: web
    type: webapp
    build:
      dockerfile: Dockerfile
    endpoints:
      - name: http
        displayName: HTTP Endpoint
        service:
          basePath: /
          port: 8080
        type: REST
        networkVisibilities:
          - Public
