schemaVersion: "1.2"
name: hello-choreo
services:
  - name: web
    type: webapp
    build:
      dockerfile: Dockerfile
    endpoints:
      - name: my-service-endpoint
        displayName: My Service Endpoint
        service:
          basePath: /
          port: 8080
        type: REST
        networkVisibilities:
          - Public
